// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MMLServer.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for RuntimeType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RuntimeType
    {
        [EnumMember(Value = "R")]
        R,
        [EnumMember(Value = "Python")]
        Python
    }
    internal static class RuntimeTypeEnumExtension
    {
        internal static string ToSerializedValue(this RuntimeType? value)  =>
            value == null ? null : ((RuntimeType)value).ToSerializedValue();

        internal static string ToSerializedValue(this RuntimeType value)
        {
            switch( value )
            {
                case RuntimeType.R:
                    return "R";
                case RuntimeType.Python:
                    return "Python";
            }
            return null;
        }

        internal static RuntimeType? ParseRuntimeType(this string value)
        {
            switch( value )
            {
                case "R":
                    return RuntimeType.R;
                case "Python":
                    return RuntimeType.Python;
            }
            return null;
        }
    }
}
