// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MMLServer.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for WebServiceRuntimeType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WebServiceRuntimeType
    {
        [EnumMember(Value = "R")]
        R,
        [EnumMember(Value = "Python")]
        Python,
        [EnumMember(Value = "Realtime")]
        Realtime
    }
    internal static class WebServiceRuntimeTypeEnumExtension
    {
        internal static string ToSerializedValue(this WebServiceRuntimeType? value)  =>
            value == null ? null : ((WebServiceRuntimeType)value).ToSerializedValue();

        internal static string ToSerializedValue(this WebServiceRuntimeType value)
        {
            switch( value )
            {
                case WebServiceRuntimeType.R:
                    return "R";
                case WebServiceRuntimeType.Python:
                    return "Python";
                case WebServiceRuntimeType.Realtime:
                    return "Realtime";
            }
            return null;
        }

        internal static WebServiceRuntimeType? ParseWebServiceRuntimeType(this string value)
        {
            switch( value )
            {
                case "R":
                    return WebServiceRuntimeType.R;
                case "Python":
                    return WebServiceRuntimeType.Python;
                case "Realtime":
                    return WebServiceRuntimeType.Realtime;
            }
            return null;
        }
    }
}
